<?php
    session_start();
?>
<?php
    if($_SESSION['email']){
        session_unset();
        session_destroy();
        header("location:uindex.php");
    }
    else{
        header("location:uindex.php");
    }
?>